name: Run Tests on Pull Request to Master
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3
      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0 # Use the appropriate .NET version

      # Restore dependencies
      - name: Restore Dependencies
        run: dotnet restore Bank.sln

      # Build the solution
      - name: Build Solution
        run: dotnet build Bank.sln --configuration Release --no-restore

      # Run tests
      - name: Run Tests
        run: dotnet test Bank.sln --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"

      # Upload test results (optional)
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/test_results.trx'
      - name: Annotate Failures
        uses: EnricoMi/action-dotnet-test-report@v3
        with:
          dotnet-test-arguments: --logger "trx;LogFileName=test_results.trx"
          annotate: true
          check-failures: true
      
